# Generated by Django 3.2.7 on 2021-09-09 13:25

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('login', models.CharField(max_length=200)),
                ('html_url', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('USR', 'User'), ('ORG', 'Organization')], default='USR', max_length=3)),
                ('info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('full_name', models.CharField(max_length=200)),
                ('private', models.BooleanField()),
                ('html_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(null=True)),
                ('info', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
